//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworkHero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWork
    {
        public int HomeWorkID { get; set; }
        public int UserID { get; set; }
        public int MonsterID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Class { get; set; }
        public string Due_Date { get; set; }
        public int isComplete { get; set; }
    
        public virtual Monster Monster { get; set; }
    }
}
